name: Deploy to Vercel

on:
  push:
    branches:
      - main # Mude para o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }} # Configure esse segredo nas configurações do seu repositório
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }} # Configure esse segredo nas configurações do seu repositório
